### ISSUE TITLE
!analyze -v does not output like WinDbg

### ISSUE THREAD

**Issue by technoscavenger** [sukesh-ak/AutoDebug#1]
I have added !analyze -v in commandlist.txt but it does not seem to do anything. Do I need to do something else to make it to work?

**Comment by sukesh-ak** [comment]
Please share the output. Usually its because the required DLL files are not there and the extension path is not set correctly.
Anything starting with ! is an extension command.

Its mentioned here
https://github.com/sukesh-ak/AutoDebug/wiki/Setup-for-automation

**Comment by sukesh-ak** [comment]
Example of using extension is here
https://github.com/sukesh-ak/AutoDebug/wiki/Advanced-Usage

**Comment by technoscavenger** [comment]
```
C:\prj>.\AutoDebug.exe C:\tmp\somefiles.exe.8284.dmp
[Command]> .time
Debug session time: Tue Nov 10 13:39:36.000 2020 (UTC - 6:00)
System Uptime: 12 days 17:44:50.834
Process Uptime: 0 days 9:09:35.000
  Kernel time: 0 days 0:00:22.000
  User time: 0 days 0:01:20.000

[Command]> .sympath
Symbol search path is: SRV*c:\symbols*\\somemachine\Store;http://msdl.microsoft.com/download/symbols
Expanded Symbol search path is: srv*c:\symbols*\\somemachine\Store;http://msdl.microsoft.com/download/symbols

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       SRV*c:\symbols*\\somemachine\Store
Deferred                                       http://msdl.microsoft.com/download/symbols

[Command]> !analyze -v


C:\prj>

```
Note: I have commented out the last the following lines:
                /// Sample ClrMD v2 snippets to mimic SOS Windbg extension commands
                /// Check the sample code in ClrDebugger.cs file
                //dbg.ClrDacInfo();
                //dbg.DumpHeap(StatsOnly : false);
                //dbg.DumpModules();

**Comment by technoscavenger** [comment]
commandList.txt contains the following:

.time
.sympath
!analyze -v

**Comment by technoscavenger** [comment]
OK, copied the following files locally:
dbgeng.dll
dbghelp.dll
srcsrv.dll
symsrv.dll

And commandList.txt has the following:
.time
.sympath
.extpath+ "C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\winext"
!analyze -v

Now it works!
